CREATE SMALLFILE TABLESPACE SOLDB 
    DATAFILE 
        'D:\Oracle\12c\oradata\orcl\SOLDB.DBF' SIZE 10485760 AUTOEXTEND ON NEXT 5242880 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
