-- SELECT INTO
-- 단일행 데이터 저장

SET SERVEROUTPUT ON;

DECLARE
   V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
    SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW   -- 검색 결과를 변수(V_DEPT_ROW)에 저장, 검색결과가 1개여야 한다.
        FROM DEPT
        WHERE DEPTNO = 40;
        
   DBMS_OUTPUT.PUT_LINE('DEPTNO : ' || V_DEPT_ROW.DEPTNO);
   DBMS_OUTPUT.PUT_LINE('DNAME : ' || V_DEPT_ROW.DNAME);
   DBMS_OUTPUT.PUT_LINE('LOC : ' || V_DEPT_ROW.LOC);
END;
/